CREATE TABLE `bungie_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`apiKey` varchar(512) NOT NULL,
	`bungieName` varchar(256),
	`membershipType` int,
	`membershipId` varchar(64),
	`primaryCharacterId` varchar(64),
	`characterClass` varchar(32),
	`lightLevel` int,
	`autoSync` boolean NOT NULL DEFAULT true,
	`lastSyncAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bungie_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bungie_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`activityId` varchar(64) NOT NULL,
	`instanceId` varchar(64),
	`period` timestamp NOT NULL,
	`mode` int NOT NULL,
	`modeName` varchar(64),
	`mapHash` bigint,
	`mapName` varchar(128),
	`durationSeconds` int,
	`isPrivate` boolean NOT NULL DEFAULT false,
	`kills` int NOT NULL DEFAULT 0,
	`deaths` int NOT NULL DEFAULT 0,
	`assists` int NOT NULL DEFAULT 0,
	`kd` decimal(6,3),
	`kda` decimal(6,3),
	`efficiency` decimal(6,3),
	`score` int DEFAULT 0,
	`standing` int,
	`teamScore` int,
	`opponentScore` int,
	`precisionKills` int,
	`superKills` int,
	`grenadeKills` int,
	`meleeKills` int,
	`abilityKills` int,
	`longestKillSpree` int,
	`pgcrData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bungie_matches_id` PRIMARY KEY(`id`),
	CONSTRAINT `bungie_matches_activityId_unique` UNIQUE(`activityId`)
);
--> statement-breakpoint
CREATE TABLE `match_correlations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`bungieMatchId` int NOT NULL,
	`crucibleMatchId` int,
	`avgLatencyMs` decimal(8,3),
	`maxLatencyMs` decimal(8,3),
	`minLatencyMs` decimal(8,3),
	`avgJitterMs` decimal(8,3),
	`maxJitterMs` decimal(8,3),
	`packetLossPercent` decimal(5,2),
	`lagSpikeCount` int DEFAULT 0,
	`performanceImpact` enum('positive','neutral','negative') DEFAULT 'neutral',
	`insights` json,
	`networkStartTime` timestamp,
	`networkEndTime` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `match_correlations_id` PRIMARY KEY(`id`)
);
