CREATE TABLE `achievement_definitions` (
	`id` varchar(64) NOT NULL,
	`name` varchar(128) NOT NULL,
	`description` text NOT NULL,
	`category` enum('combat','boss','flawless','score','class','weapon','survival','collection','special') NOT NULL,
	`tier` enum('bronze','silver','gold','platinum','exotic') NOT NULL,
	`targetValue` int NOT NULL,
	`rewardType` enum('title','emblem','shader','points') DEFAULT 'points',
	`rewardValue` varchar(256),
	`triumphPoints` int NOT NULL DEFAULT 10,
	`iconUrl` varchar(512),
	`isSecret` boolean NOT NULL DEFAULT false,
	`prerequisiteId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `achievement_definitions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `achievement_notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`achievementId` varchar(64) NOT NULL,
	`shown` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `achievement_notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_achievements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`achievementId` varchar(64) NOT NULL,
	`currentValue` int NOT NULL DEFAULT 0,
	`isCompleted` boolean NOT NULL DEFAULT false,
	`completedAt` timestamp,
	`claimedReward` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_achievements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_triumph_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`totalKills` int NOT NULL DEFAULT 0,
	`dregKills` int NOT NULL DEFAULT 0,
	`vandalKills` int NOT NULL DEFAULT 0,
	`captainKills` int NOT NULL DEFAULT 0,
	`thrallKills` int NOT NULL DEFAULT 0,
	`acolyteKills` int NOT NULL DEFAULT 0,
	`knightKills` int NOT NULL DEFAULT 0,
	`goblinKills` int NOT NULL DEFAULT 0,
	`hobgoblinKills` int NOT NULL DEFAULT 0,
	`minotaurKills` int NOT NULL DEFAULT 0,
	`ogreKills` int NOT NULL DEFAULT 0,
	`servitorKills` int NOT NULL DEFAULT 0,
	`hydraKills` int NOT NULL DEFAULT 0,
	`flawlessOgre` int NOT NULL DEFAULT 0,
	`flawlessServitor` int NOT NULL DEFAULT 0,
	`flawlessHydra` int NOT NULL DEFAULT 0,
	`autoRifleKills` int NOT NULL DEFAULT 0,
	`handCannonKills` int NOT NULL DEFAULT 0,
	`pulseRifleKills` int NOT NULL DEFAULT 0,
	`rocketLauncherKills` int NOT NULL DEFAULT 0,
	`titanGamesPlayed` int NOT NULL DEFAULT 0,
	`hunterGamesPlayed` int NOT NULL DEFAULT 0,
	`warlockGamesPlayed` int NOT NULL DEFAULT 0,
	`titanWins` int NOT NULL DEFAULT 0,
	`hunterWins` int NOT NULL DEFAULT 0,
	`warlockWins` int NOT NULL DEFAULT 0,
	`highestScore` int NOT NULL DEFAULT 0,
	`totalScore` bigint NOT NULL DEFAULT 0,
	`gamesPlayed` int NOT NULL DEFAULT 0,
	`highestWave` int NOT NULL DEFAULT 0,
	`highestLevel` int NOT NULL DEFAULT 0,
	`cosmodromeClears` int NOT NULL DEFAULT 0,
	`europaClears` int NOT NULL DEFAULT 0,
	`dreamingCityClears` int NOT NULL DEFAULT 0,
	`commonEngrams` int NOT NULL DEFAULT 0,
	`uncommonEngrams` int NOT NULL DEFAULT 0,
	`rareEngrams` int NOT NULL DEFAULT 0,
	`legendaryEngrams` int NOT NULL DEFAULT 0,
	`exoticEngrams` int NOT NULL DEFAULT 0,
	`abilitiesUsed` int NOT NULL DEFAULT 0,
	`supersUsed` int NOT NULL DEFAULT 0,
	`totalTriumphPoints` int NOT NULL DEFAULT 0,
	`titlesEarned` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_triumph_stats_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_triumph_stats_userId_unique` UNIQUE(`userId`)
);
